/**
 * @see https://tailwindcss.com/docs/content-configuration
 * @see https://tailwindcss.com/docs/dark-mode
 * @see https://tailwindcss.com/docs/presets
 */

module.exports = {

    /**
     * You must add the path whenever any css class is added outside the
     * default location, which is the ./resources folder.
     * Otherwise, the class will not be generated by the compiler and the
     * defined style will not be applied.
     */
    content: [
        './resources/**/*.blade.php',
        './resources/**/*.js'
    ],

    safelist: [
        'icon'
    ],

    darkMode: 'class',

    theme: {
        extend: {}
    },

    plugins: []
};
